CREATE TABLE Users (
	Id INT PRIMARY KEY IDENTITY(1,1),
	Email NVARCHAR(255) NOT NULL,
	PasswordHash NVARCHAR(MAX) NOT NULL,
	Tag NVARCHAR(50) NOT NULL,
	DisplayName NVARCHAR(50) NOT NULL,
	AvatarUrl NVARCHAR(MAX) NULL,
	Role NVARCHAR(20) NOT NULL DEFAULT 'User',
	CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
	IsDeleted BIT NOT NULL DEFAULT 0,

	CONSTRAINT UQ_Users_Email UNIQUE(Email),
	CONSTRAINT UQ_Users_Tag UNIQUE(Tag)
);
