CREATE TABLE Boards (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Title NVARCHAR(100) NOT NULL,
    Description NVARCHAR(500) NULL,

    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
	CreatedBy INT NOT NULL,

	UpdatedAt DATETIME2 NULL DEFAULT GETDATE(),
	UpdatedBy INT NULL,

	IsArchived BIT NOT NULL DEFAULT 0,

	CONSTRAINT FK_Boards_CreatedBy FOREIGN KEY (CreatedBy) REFERENCES Users(Id),
	CONSTRAINT FK_Boards_UpdatedBy FOREIGN KEY (UpdatedBy) REFERENCES Users(Id),
	CONSTRAINT UQ_Boards_CreatedBy Unique(UpdatedBy)
);