CREATE TABLE Columns (
	Id INT PRIMARY KEY IDENTITY(1,1),
	BoardId INT NOT NULL,
	Title NVARCHAR(50) NOT NULL,
	[Order] INT NOT NULL DEFAULT 0,

	CreatedBy INT NOT NULL,
	UpdatedBy INT NULL,

	CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
	UpdatedAt DATETIME2 NULL DEFAULT GETDATE(),
	
	CONSTRAINT FK_Columns_BoardId FOREIGN KEY (BoardId) REFERENCES Boards(Id) ON DELETE CASCADE,
	CONSTRAINT FK_Columns_CreatedBy FOREIGN KEY (CreatedBy) REFERENCES Users(Id),
	CONSTRAINT FK_Columns_UpdatedBy FOREIGN KEY (UpdatedBy) REFERENCES Users(Id)
);