CREATE TABLE Tasks (
	Id INT PRIMARY KEY IDENTITY(1,1),
	ColumnId INT NOT NULL,
	Title NVARCHAR(200) NOT NULL,
	Description NVARCHAR(MAX) NULL,

	Priority INT NOT NULL DEFAULT 1,
	DueDate DATETIME2 NULL,
	Position INT NOT NULL DEFAULT 0,

	AssigneeId INT NULL,

	CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
	UpdatedAt DATETIME2 NULL,

	CreatedBy INT NOT NULL,
	UpdatedBy INT NULL,

	CONSTRAINT FK_Tasks_ColumnId FOREIGN KEY (ColumnId) REFERENCES Columns(Id),
	CONSTRAINT FK_Tasks_Assignee FOREIGN KEY (AssigneeId) REFERENCES Users(Id),
	CONSTRAINT FK_Tasks_CreatedBy FOREIGN KEY (CreatedBy) REFERENCES Users(Id),
	CONSTRAINT FK_Tasks_UpdatedBy FOREIGN KEY (UpdatedBy) REFERENCES Users(Id)
);