CREATE TABLE BoardMembers (
	Id INT PRIMARY KEY IDENTITY(1,1),

	UserId INT NOT NULL,
	BoardId INT NOT NULL,

	Role NVARCHAR(20) NOT NULL DEFAULT 'Editor',
	JoinedAt DATETIME2 NOT NULL DEFAULT GETDATE(),

	CONSTRAINT FK_BoardMembers_Boards FOREIGN KEY (BoardId) REFERENCES Boards(Id) ON DELETE CASCADE,
    CONSTRAINT FK_BoardMembers_Users FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,

	CONSTRAINT UQ_BoardMembers_UserPerBoard UNIQUE(BoardId, UserId)
);