ALTER TABLE Columns
DROP CONSTRAINT FK_Columns_BoardId;

ALTER TABLE Columns
ADD CONSTRAINT FK_Columns_BoardId
FOREIGN KEY (BoardId)
REFERENCES Boards(Id)
ON DELETE CASCADE;

ALTER TABLE Tasks
DROP CONSTRAINT FK_Tasks_ColumnId;

ALTER TABLE Tasks
ADD CONSTRAINT FK_Tasks_ColumnId
FOREIGN KEY (ColumnId)
REFERENCES Columns(Id)
ON DELETE CASCADE;
