CREATE TABLE RefreshTokens (
	Id INT PRIMARY KEY IDENTITY(1,1),
	Token NVARCHAR(100) NOT NULL,
	UserId INT NOT NULL,
	ExpiresAt DATETIME2 NOT NULL,
	CreatedAt DATETIME2 NOT NULL,
	RevokedAt DATETIME2 NULL,

	CONSTRAINT FK_RefreshTokens_Users FOREIGN KEY (UserId) REFERENCES Users(Id)
);