CREATE TABLE Notifications (
	Id INT PRIMARY KEY IDENTITY(1,1),
	UserId INT NOT NULL,
	Payload NVARCHAR(MAX) NOT NULL,
	Type TINYINT NOT NULL,
	Title NVARCHAR(70) NOT NULL,
	Message NVARCHAR(200) NOT NULL,
	IsRead BIT DEFAULT 0,
	CreatedAt DATETIME2 DEFAULT GETDATE()

	CONSTRAINT Notifications_UserId FOREIGN KEY (UserId) REFERENCES Users(Id),
);