CREATE TABLE Comments (
	Id INT PRIMARY KEY IDENTITY(1,1),
	TaskId INT NOT NULL,
	CreatedBy INT NOT NULL,
	Content NVARCHAR(MAX) NOT NULL,
	CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
	UpdatedBy INT NULL,
	UpdatedAt DATETIME2 NULL
);