CREATE TABLE Attachments
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	TaskId INT NOT NULL,
	CreatedBy INT NOT NULL,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	FileUrl NVARCHAR(MAX) NOT NULL,
	Name NVARCHAR(255) NOT NULL,
	SizeKB FLOAT NOT NULL,
	FOREIGN KEY (TaskId) REFERENCES Tasks(Id) ON DELETE CASCADE,
	FOREIGN KEY (CreatedBy) REFERENCES Users(Id)
);